### PR TITLE
rfc-1: schema revision

### PR DESCRIPTION
**Pull request by vyzo**
Per our discussion and implementation experience so far:
- store data object metadata in a meta field
- normalize reference field in chain cells
- add ArtefactLinkCells for dedup/similarity linking of artefacts

### CODE REVIEW

**Comment by parkan** [comment]
This looks good and actually upon another reading, maybe some of these specialized cell types actually do make sense.

**Comment by parkan** [comment]
Forgot one thing: we also need a "derived_from" field to point to a raw metadata blob that the update cell was sourced from

**Comment by vyzo** [comment]
there is already an artefactOrigin field that points to the original canonical record and there is the meta that can contain additional metadata, do we really need another field?

**Comment by parkan** [comment]
ah, wasn't sure what the semantics of `artefactOrigin` were, that's fine

**Pull request merged**
