### PR TITLE
intercept rpc calls and log unique client addresses

### PR DESCRIPTION
**Pull request by yusefnapora**
so far just prints the client's `SocketAddress` to the console.  needs to be wired up to the influxdb metrics logger

### CODE REVIEW

**Comment by vyzo** [comment]
can you log it instead of printing so that we can actually see them?

**Comment by yusefnapora** [comment]
sure, one sec :)

**Comment by yusefnapora** [comment]
@vyzo, does this log output look alright:

```
[18/07/2016:15:50:32 +0000] [grpc-default-executor-0] INFO UniqueClientIP - /0:0:0:0:0:0:0:1
```

It looks like the localhost transport  at least uses ip6 - I imagine we'll see some ip4 from real-world clients also.

I'm just storing the hashCode of the addresses in a mutable `HashSet` to track unique connections.  It will lose the history if the service restarts, but that's probably fine; it doesn't seem worth the bother of persisting the set of connections.

Should I try wiring this up to influxdb also?

**Comment by vyzo** [comment]
:+1:

**Pull request merged**
