### PR TITLE
PersistentDatastore: multiple write threads

### PR DESCRIPTION
**Pull request by vyzo**
Adds multiple threads for background writing in PersistentDatastore in order to maximize dynamo throughput.

### CODE REVIEW

**Comment by bigs** [comment]
LGTM. generally array backed concurrent queues are faster but this seems fine

**Comment by vyzo** [comment]
Well, we need the background threads to block until a new datum becomes available and concurrent queues don't see to offer take in the interface.

**Comment by vyzo** [comment]
Oh, wait BlockingArrayQueue has take/put methods. I can switch the implementation to use it.

**Comment by vyzo** [comment]
hrm, it requires a capacity bound to be set and blocks the caller thread if capacity is exceeded, which is a problem with the semantics expected by the state machine. I'll keep the linked deque.

**Comment by bigs** [comment]
sounds good

**Comment by parkan** [comment]
The recommended way to deal with multithreading is through `ExecutorService` now, rather than calling `Thread` directly (you can do this with or without futures)

**Pull request merged**
